package app.com.uicollections;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import app.com.uicollections.WallpaperURL;

import app.com.uicollections.WallpaperURLDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wallpaperURLDaoConfig;

    private final WallpaperURLDao wallpaperURLDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wallpaperURLDaoConfig = daoConfigMap.get(WallpaperURLDao.class).clone();
        wallpaperURLDaoConfig.initIdentityScope(type);

        wallpaperURLDao = new WallpaperURLDao(wallpaperURLDaoConfig, this);

        registerDao(WallpaperURL.class, wallpaperURLDao);
    }
    
    public void clear() {
        wallpaperURLDaoConfig.getIdentityScope().clear();
    }

    public WallpaperURLDao getWallpaperURLDao() {
        return wallpaperURLDao;
    }

}
