package app.com.uicollections;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WALLPAPER_URL".
 */
public class WallpaperURL {

    /** Not-null value. */
    private String URL;

    public WallpaperURL() {
    }

    public WallpaperURL(String URL) {
        this.URL = URL;
    }

    /** Not-null value. */
    public String getURL() {
        return URL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setURL(String URL) {
        this.URL = URL;
    }

}
