package app.com.uicollections.android.ui_collections.POJO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import app.com.uicollections.android.ui_collections.POJO.Note;
import app.com.uicollections.android.ui_collections.POJO.Customer;
import app.com.uicollections.android.ui_collections.POJO.Order;
import app.com.uicollections.android.ui_collections.POJO.WallpaperURL;

import app.com.uicollections.android.ui_collections.POJO.NoteDao;
import app.com.uicollections.android.ui_collections.POJO.CustomerDao;
import app.com.uicollections.android.ui_collections.POJO.OrderDao;
import app.com.uicollections.android.ui_collections.POJO.WallpaperURLDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig wallpaperURLDaoConfig;

    private final NoteDao noteDao;
    private final CustomerDao customerDao;
    private final OrderDao orderDao;
    private final WallpaperURLDao wallpaperURLDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        wallpaperURLDaoConfig = daoConfigMap.get(WallpaperURLDao.class).clone();
        wallpaperURLDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        wallpaperURLDao = new WallpaperURLDao(wallpaperURLDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Customer.class, customerDao);
        registerDao(Order.class, orderDao);
        registerDao(WallpaperURL.class, wallpaperURLDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        wallpaperURLDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public WallpaperURLDao getWallpaperURLDao() {
        return wallpaperURLDao;
    }

}
