package app.com.uicollections.android.ui_collections.POJO;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import app.com.uicollections.android.ui_collections.POJO.WallpaperURL;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WALLPAPER_URL".
*/
public class WallpaperURLDao extends AbstractDao<WallpaperURL, Void> {

    public static final String TABLENAME = "WALLPAPER_URL";

    /**
     * Properties of entity WallpaperURL.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property URL = new Property(0, String.class, "URL", false, "URL");
    };


    public WallpaperURLDao(DaoConfig config) {
        super(config);
    }
    
    public WallpaperURLDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WALLPAPER_URL\" (" + //
                "\"URL\" TEXT NOT NULL );"); // 0: URL
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WALLPAPER_URL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WallpaperURL entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getURL());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public WallpaperURL readEntity(Cursor cursor, int offset) {
        WallpaperURL entity = new WallpaperURL( //
            cursor.getString(offset + 0) // URL
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WallpaperURL entity, int offset) {
        entity.setURL(cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(WallpaperURL entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(WallpaperURL entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
